# This file was generated by GoReleaser. DO NOT EDIT.
cask "example-go-cask" do
  desc ""
  homepage ""
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "example-go-cask"

  module GitHubHelper
    def self.get_asset_api_url(tag, name)
      require "utils/github"

      release = GitHub.get_release("sushichan044", "example-go-cask", tag)

      release["assets"].find { |asset| asset["name"] == name }["url"]
    end

    def self.token
      require "utils/github"

      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]

      unless @github_token
        @github_token = GitHub::API.credentials
        raise CurlDownloadStrategyError, "Failed to retrieve token" if @github_token.nil? || @github_token.empty?
      end

      @github_token
    end
  end

  on_macos do
    url "#{GitHubHelper.get_asset_api_url("v0.0.3", "example-go-cask_Darwin_all.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    sha256 "98a7ca8929311b89a39af64348128f9a4c2a481cecc75a9d81e0939c5a4ce98f"
  end

  on_linux do
    on_intel do
      url "#{GitHubHelper.get_asset_api_url("v0.0.3", "example-go-cask_Linux_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "48c3c7bb03c2684e9bba09df99673770f57a39c0c96f6e23b08ed8b82c0466b9"
    end
    on_arm do
      url "#{GitHubHelper.get_asset_api_url("v0.0.3", "example-go-cask_Linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "3887a579d83fde3d8b7a130ce7e0956de7e10d2453ce25ae86367d5b25f9c957"
    end
  end

  # No zap stanza required
end
