# This file was generated by GoReleaser. DO NOT EDIT.
cask "example-go-cask" do
  desc ""
  homepage ""
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "example-go-cask"

  on_macos do
    url "#{GitHubHelper.get_asset_api_url(v0.0.1, example-go-cask_Darwin_all.tar.gz)}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    sha256 "51668a232151925b39538f3f09a55ab353285a3aaf4e9a57737f9198df2cff54"
  end

  on_linux do
    on_intel do
      url "#{GitHubHelper.get_asset_api_url(v0.0.1, example-go-cask_Linux_x86_64.tar.gz)}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "14fe5da3d2ee866f060b6d71ad3095b6cc39995b2bda65b304963e45a8731671"
    end
    on_arm do
      url "#{GitHubHelper.get_asset_api_url(v0.0.1, example-go-cask_Linux_arm64.tar.gz)}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "c199bbb48fc92cbaa965090bc409716f171c2c93bdd0e670500d51ef9cc69d69"
    end
  end

  module GitHubHelper
    def self.get_asset_api_url(tag, name)
      require "utils/github"

      release = GitHub.get_release("sushichan044", "homebrew-experimental-tap", tag)

      release.assets.find { |asset| asset.name == name }.url
    end

    def self.token
      require "utils/github"

      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]

      unless @github_token
        @github_token = GitHub::API.credentials
        raise CurlDownloadStrategyError, "Failed to retrieve token" if @github_token.nil? || @github_token.empty?
      end

      @github_token
    end
  end

  # No zap stanza required
end
